name: Update README.md
on:
  release:
  schedule:
    - cron: "0 0,12 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Node Environment
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: npm install chartscii node-fetch --only=prod

      - name: Get CodeStats Graph
        shell: bash
        id: get-codestat-graph
        run: node ./.github/workflows/getStats.js

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.8.0
        with:
          commit_message: Update Graph
