name: Metrics
on:
  schedule:
    - cron: "0 0,6/3 * * *"
  push:
    paths:
      - ".github/workflows/**"
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_timezone: Europe/Amsterdam
          repositories_forks: yes
          config_order: base.header, wakatime, anilist, base.activity+community, base.repositories, habits
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_threshold: 2%
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_followup: yes
          plugin_lines: yes
          plugin_traffic: yes
          plugin_anilist: yes
          plugin_anilist_sections:
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_sections: time, languages, editors, os
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: B
          plugin_achievements_only: polyglot, stargazer, maintainer, developer, scripter, explorer, inspirer
