name: Metrics
on:
  schedule:
    - cron: "0 0,6/3 * * *"
  push:
    paths:
      - ".github/workflows/**"
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_timezone: Europe/Amsterdam
          repositories_forks: yes
          repositories_skipped: cheat-engine, tachiyomi-extensions, postcss, VirtualXposed_12
          config_order: base.header, wakatime, anilist, base.activity+community, base.repositories, habits
          optimize: css, xml
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_threshold: 2%
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_followup: yes
          plugin_lines: yes
          plugin_traffic: yes
          plugin_anilist: yes
          plugin_anilist_user: ardittristan
          plugin_anilist_sections: ""
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_sections: time, languages, editors, os
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_music: yes
          plugin_music_provider: lastfm
          plugin_music_token: ${{ secrets.LASTFM_KEY }}
          plugin_music_user: ardittristan
          plugin_music_mode: top
          plugin_steam: yes
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam_user: "76561198131351418"
          plugin_steam_games_ignored: "1546320"
          plugin_steam_achievements_limit: "0"
          plugin_achievements_only: polyglot, stargazer, maintainer, developer, scripter, explorer, inspirer
